name: movie_api
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  http: ^0.12.2
  built_value: ^7.1.0
  built_collection: ^4.3.2
  redux: ^4.0.0+3
  flutter_redux: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: '>1.0.0 <2.0.0'
  built_value_generator: ^7.1.0

flutter:

  uses-material-design: true
